const LOAD_FETCHING_DATA = "LOAD_FETCHING_DATA";
const GET_SUCCESS_RESPONSE = "GET_SUCCESS_RESPONSE";
const GET_ERROR_RESPONSE = "GET_ERROR_RESPONSE";
const ADD_FAVOURITE_POKEMON = "ADD_FAVOURITE_POKEMON"

export { LOAD_FETCHING_DATA, GET_SUCCESS_RESPONSE, GET_ERROR_RESPONSE, ADD_FAVOURITE_POKEMON };