const LOAD_FETCHING_DATA = "LOAD_FETCHING_DATA";
const GET_SUCCESS_RESPONSE = "GET_SUCCESS_RESPONSE";
const GET_ERROR_RESPONSE = "GET_ERROR_RESPONSE";

export { LOAD_FETCHING_DATA, GET_SUCCESS_RESPONSE, GET_ERROR_RESPONSE };